package com.comonier.netheritesilkspawners;

import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.CreatureSpawner;
import org.bukkit.entity.EnderDragon;
import org.bukkit.entity.Wither;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockPistonExtendEvent;
import org.bukkit.event.block.BlockPistonRetractEvent;
import org.bukkit.event.entity.EntityChangeBlockEvent;
import org.bukkit.event.entity.EntityInteractEvent;
import org.bukkit.event.entity.SpawnerSpawnEvent;
import org.bukkit.event.weather.LightningStrikeEvent;
import org.bukkit.persistence.PersistentDataType;

/**
 * Advanced security layer to block fake spawners, illegal physics, 
 * and entity-based block griefing.
 */
public class SpawnerGlobalBlocker implements Listener {

    private final Main plugin;

    public SpawnerGlobalBlocker(Main plugin) {
        this.plugin = plugin;
    }

    /**
     * Blocks entity spawning from any block that is not a legitimate vanilla Spawner.
     * This prevents other plugins from creating "fake" spawners using non-spawner blocks.
     */
    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onSpawnerSpawn(SpawnerSpawnEvent event) {
        Block block = event.getSpawner().getBlock();

        // 1. Check if the block type is actually a SPAWNER
        if (block.getType() != Material.SPAWNER) {
            event.setCancelled(true);
            return;
        }

        // 2. Check if the Spawner has our legitimacy tag (NBT)
        // If it was placed by a player or generated by the world, it must have the tag.
        CreatureSpawner spawner = event.getSpawner();
        if (!spawner.getPersistentDataContainer().has(Main.SPAWNER_KEY, PersistentDataType.BYTE)) {
            
            // Note: If you notice natural world-gen spawners are being blocked, 
            // you can add a logic here to tag them on their first spawn attempt.
            event.setCancelled(true);
        }
    }

    /**
     * Blocks Wither, EnderDragon and Enderman from affecting Spawner blocks.
     */
    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onEntityChangeBlock(EntityChangeBlockEvent event) {
        if (event.getBlock().getType() == Material.SPAWNER) {
            if (event.getEntity() instanceof Wither || event.getEntity() instanceof EnderDragon) {
                event.setCancelled(true);
            }
            // Prevents any entity-based block transformation
            event.setCancelled(true);
        }
    }

    /**
     * Prevents pistons from moving spawners (Strict immovable block logic).
     */
    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onPistonExtend(BlockPistonExtendEvent event) {
        for (Block block : event.getBlocks()) {
            if (block.getType() == Material.SPAWNER) {
                event.setCancelled(true);
                return;
            }
        }
    }

    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onPistonRetract(BlockPistonRetractEvent event) {
        for (Block block : event.getBlocks()) {
            if (block.getType() == Material.SPAWNER) {
                event.setCancelled(true);
                return;
            }
        }
    }

    /**
     * Protects spawners from lightning strikes.
     */
    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onLightningStrike(LightningStrikeEvent event) {
        if (event.getLightning().getLocation().getBlock().getType() == Material.SPAWNER) {
            event.setCancelled(true);
        }
    }

    /**
     * Prevents general entity interaction/damage to the block.
     */
    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onEntityInteract(EntityInteractEvent event) {
        if (event.getBlock().getType() == Material.SPAWNER) {
            event.setCancelled(true);
        }
    }
}
